services:
  - type: web
    name: carimakan-backend
    env: node
    rootDir: express
    buildCommand: npm install --omit=dev
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
