@echo off
cd /d "%~dp0"
echo Starting backend...
start "EXPRESS" cmd /k "cd /d "%~dp0express" && npm start"
echo Starting frontend...
start "REACT" cmd /k "cd /d "%~dp0react" && npm run dev -- --host 0.0.0.0"
echo Both servers are starting...
pause
